[build]
  command = "yarn install pug-cli; node node_modules/pug-cli/index.js pug/ --out ./public"
  functions = "functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index/:splat"
  status  = 200
  force = true
